backend:
  name: github
  repo: AndrewMatsiash/andrewmatsiash.github.io
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/images/
public_folder: images/
site_url: https://andrewmatsiash.github.io/

collections:
  - name: 'Blog'
    label: 'Post'
    folder: 'content/blogs'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - label: 'SEO'
        name: 'SEO'
        widget: 'object'
        fields:
          - { label: 'description', name: 'description', widget: 'string' }
          - { label: 'keywords', name: 'keywords', widget: 'string' }
          - { label: 'author', name: 'author', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Preview', name: 'image', widget: 'image' }
      - { label: 'Avatar', name: 'avatar', widget: 'image', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Categories', name: 'blog_categories', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown', mode: 'raw' }
  - name: 'Testimonials'
    label: 'Testimonial'
    folder: 'content/testimonials'
    create: true
    editor:
      preview: true
    fields:
      - { label: name, name: name, widget: string }
      - { label: 'Avatar', name: 'avatar', widget: 'image' }
      - { label: position, name: position, widget: string }
      - { label: description, name: description, widget: text }
  - name: 'Cases'
    label: 'Case'
    folder: 'content/cases'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - label: 'SEO'
        name: 'SEO'
        widget: 'object'
        fields:
          - { label: 'description', name: 'description', widget: 'string' }
          - { label: 'keywords', name: 'keywords', widget: 'string' }
          - { label: 'author', name: 'author', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Preview', name: 'image', widget: 'image' }
      - { label: 'Categories', name: 'case_categories', widget: 'list' }
      - label: 'Section General Information'
        name: 'project_info'
        widget: 'object'
        fields:
          - { label: 'client', name: 'client', widget: 'string' }
          - { label: 'location', name: 'location', widget: 'string' }
          - { label: 'industry', name: 'industry', widget: 'string' }
          - { label: 'client_since', name: 'client_since', widget: 'number' }
          - { label: 'type', name: 'type', widget: 'string' }
          - {
              label: 'engagement_model',
              name: 'engagement_model',
              widget: 'string',
            }
          - { label: 'duration', name: 'duration', widget: 'string' }
          - { label: 'staff', name: 'staff', widget: 'text' }
      - label: 'Section Challenge'
        name: 'challenge'
        widget: 'object'
        fields:
          - { label: 'subtitle', name: 'subtitle', widget: 'string' }
          - label: 'issues'
            name: 'issues'
            widget: 'list'
            max: 9
            fields:
              - { label: 'title', name: 'title', widget: 'string' }
              - { label: 'description', name: 'description', widget: 'string' }
      - label: 'Section Solution Table'
        name: 'body'
        widget: 'markdown'
        mode: 'raw'
      - label: 'Section Value Driven Results'
        name: 'value_driven_results'
        widget: 'object'
        fields:
          - { label: 'subtitle', name: 'subtitle', widget: 'string' }
      - label: 'Section Tools Technologies'
        name: 'tools_and_technologies'
        widget: 'list'
        max: 10
        fields:
          - { label: 'tool', name: 'tool', widget: 'string' }
          - { label: 'technologies', name: 'technologies', widget: 'string' }
      - label: 'Section Roadmap'
        name: 'roadmap'
        widget: 'list'
        fields:
          - { label: 'date', name: 'date', widget: 'string' }
          - { label: 'activities', name: 'activities', widget: 'list' }
      - label: 'Section Gallery'
        name: 'gallery_images'
        widget: 'list'
        fields:
          - { label: 'image project', name: 'image_path', widget: 'image' }
